config/routes.rb
Rails.application.routes.draw do
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
  post 'search', to: 'search#index', as: 'search'

  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    searchkick text_middle: %i[name description]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
        @results = search_for_products
    
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream:
                turbo_stream.update('products',
                                    partial: 'products/products',
                                    locals: { products: @results })
          end
        end
    end

    def suggestions
        @results = search_for_products
    
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream:
                turbo_stream.update('suggestions',
                                    partial: 'search/suggestions',
                                    locals: { results: @results })
          end
        end
    end
    
    private
    
    def search_for_products
        if params[:query].blank?
          Product.all
        else
          Product.search(params[:query], fields: %i[name description], operator: 'or', match: :text_middle)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpjuiceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= product.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this product", product, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this product", edit_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/products/_products.html.erb
<% products.each do |product| %>
    <div class="p-4 border border-gray-300 rounded-lg mt-2">
      <h2><%= product.name %></h2>
      <p><%= product.description %></p>
      <p>
        <%= link_to "Show this product", product, class: "text-blue-500" %>
      </p>
    </div>
<% end %>

app/views/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
<h1 class="text-4xl text-center mt-5 mb-4">
  Products
</h1>

<div class="flex justify-center my-8">
  <%= render "search/form", locals: { results: [] } %>
</div>

<div id="products" class="mt-4 mx-10">
  <%= render "products/products", products: @products %>
</div>
<div class="mt-4 mx-10">
  <%= link_to "New product", new_product_path, class: "rounded-lg py-3 mt-4 px-5 bg-blue-600 text-white font-medium" %>
</div>
</div>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @product %>

    <%= link_to "Edit this product", edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product", product_path(@product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/search/_form.html.erb
<%= form_with(url: search_path, method: :post, class: "w-60", data: {
    controller: "search",
    action: "keyup->search#suggestions",
    suggestions_url: search_suggestions_path,
}) do |form| %>
  <div class="relative">
    <%= form.text_field :query, data: {
            search_target: "input",
            action: "blur->search#hideSuggestions",
        },
        class: "w-full p-2 border border-gray-300 rounded-lg focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200",
        placeholder: "Search...", autocomplete: "off" %>
    <div class="absolute inset-y-0 right-0 flex items-center">
      <%= form.submit "Search", class: "p-2 text-white bg-indigo-500 rounded-lg hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600" %>
    </div>
    <div id="suggestions" class="absolute w-full mt-2 bg-white rounded-lg shadow-lg"
        data-search-target="suggestions" data-action="mousedown->search#childClicked">
      <%= render partial: "search/suggestions", locals: { results: [] } %>
    </div>
  </div>
<% end %>

app/views/search/_suggestions.html.erb
<% if results.any? %>
  <div class="absolute w-full overflow-y-auto max-h-60 bg-white rounded-lg shadow-lg">
    <% results.each do |product| %>
      <div class="p-2 border-b border-gray-300 hover:bg-gray-100">
        <%= link_to product.name, product, class: "text-blue-500" %>
      </div>
    <% end %>
  </div>
<% end %>